# Core Settings

name: Bruno Giarrizzo

description: Bruno Giarrizzo, Freelance, Developer & DevOps

description_meta: >
  Freelance DevOps and Developer. I can participate to multiple type of projects : Specific development, Refactoring, Webapps, APIs, etc

description_sidebar: >
  <p style="font-size: 0.8em;">Freelance DevOps and Developer. I can participate to multiple type of projects : Specific development, Refactoring, Webapps, APIs, etc</p>
  <p style="font-size: 0.8em;">Feel free to <a href="/onboard/">reach me</a> </p>

description_pages_posts: >
  blablabla

keywords:
  [
    Bruno,
    Giarrizzo,
    Bruno Giarrizzo,
    Freelance,
    Developer,
    DevOps,
    Ethical Hacker,
    Ethical,
    Hacker,
    Django,
    Python,
    Swift,
    Ansible,
    Terraform,
    Kubernetes,
    Infra as Code,
  ]

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.bruno-giarrizzo.fr

author_avatar: "images/photo-min.jpg"
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: bruno-giarrizzo

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-178521232-1

# Misc

social_ids:
  twitter: hyweene
  twitch: hyweene
  youtube: UCSXj4YcwcmH57INCrNAR03Q
  github: bgiarrizzo
  paypal: bgiarrizzo

email: b.giarrizzo@cyberlife.sh

paginate: 5
paginate_path: "blog/page:num/"

# -----------------------------------------
# Build settings

plugins:
  - jekyll-paginate

exclude:
  - .gitignore
  #   - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  # Blog Categories
  category:
    output: true
    permalink: /:collection/:name/
  # Resume sections exploded in markdown files
  resume:
    output: true
  # book listing in markdown files
  books:
    output: true
  # game listing in markdown files
  games:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
