version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VERSION: "3.11-bullseye"
    volumes:
      - ../:/workspaces/app/:cached
    environment:
      - "APP_VERSION=DEV_LOCAL"
      - "APP_URL=http://127.0.0.1:8000"
      - "APP_ENV=DEV"
      - "APP_DEBUG=True"
      - "APP_LOG_LEVEL=DEBUG"
      - "APP_SECRET_KEY=my-Sup3r-S3cr3t-K3y-F0r-D3v-Env!"
    user: vscode
    command: sleep infinity
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge
