version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.12-slim-bookworm"
    volumes:
      - ../:/workspaces/app/:cached
    environment:
      - "TEST=TEST"
    command: sleep infinity
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge
